name: Generar APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      # Actualizado a v4
      
      - uses: actions/setup-node@v4    # Actualizado a v4
        with:
          node-version: 18
          
      - uses: actions/setup-java@v4    # Actualizado a v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Instalar y Configurar
        run: |
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/android
          npx cap init FerenPuzzle com.feren.puzzle --web-dir www
          npx cap add android
          npx cap sync
      
      - name: Compilar APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - name: Subir APK
        uses: actions/upload-artifact@v4  # ¡AQUÍ ESTÁ EL ARREGLO!
        with:
          name: FerenPuzzle-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
